CREATE DATABASE QLDL_test
USE QLDL_test 
GO 

CREATE TABLE TOUR (
	TOUR_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TOUR_NAME NVARCHAR(500) NOT NULL,
	CUSTOMER_NUMBER INT NOT NULL,
	DESCRIPTIONS NVARCHAR(MAX),
	TOURCATEGORY_ID INT NOT NULL,
	STARTS_DATE DATETIME NOT NULL,
	ENDS_DATE DATETIME NOT NULL,
	LOCATIONS NVARCHAR(250) NOT NULL,
	GUIDE_ID INT NOT NULL,
);
GO

CREATE TABLE TOUR_CATEGORY(
	TOURCATEGORY_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TOURCATEGORY_NAME NVARCHAR(250) NOT NULL,
);

GO

ALTER TABLE TOUR
ADD FOREIGN KEY (TOURCATEGORY_ID) REFERENCES TOUR_CATEGORY(TOURCATEGORY_ID);
GO

ALTER TABLE TOUR
ADD FOREIGN KEY (GUIDE_ID) REFERENCES GUIDE(GUIDE_ID);
GO



CREATE TABLE CUSTOMER(
	CUSTOMER_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CUSTOMER_NAME NVARCHAR(250) NOT NULL,
	PHONENUMBER VARCHAR(10) NOT NULL,
	CUSTOMER_ADDRESS NVARCHAR(250),
	SEX BIT,
	EMAIL VARCHAR(100) NOT NULL,
);
GO

CREATE TABLE FEEDBACK(
	FB_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TOUR_ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	CONTENT NVARCHAR(MAX) NOT NULL,
	LIKES INT,
);
GO

ALTER TABLE FEEDBACK
ADD FOREIGN KEY (TOUR_ID) REFERENCES TOUR(TOUR_ID);
GO
ALTER TABLE FEEDBACK
ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
GO





CREATE TABLE BOOKING (
	BOOKING_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TOUR_ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	DEPARTURE_DAY DATETIME,
	DEPOSIT FLOAT 
);
GO
ALTER TABLE BOOKING
ADD FOREIGN KEY (TOUR_ID) REFERENCES TOUR(TOUR_ID);
GO
ALTER TABLE BOOKING
ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
GO


CREATE TABLE CONTRACTS(
	CONTRACTS_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	BOOKING_ID INT NOT NULL, 
	STAFF_ID INT NOT NULL,
	SIGNINGDAY DATETIME NOT NULL,
	RULES NVARCHAR(500) NOT NULL,
	TOTAL FLOAT,
);
GO

ALTER TABLE CONTRACTS
ADD FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID);
GO
ALTER TABLE CONTRACTS
ADD FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID);
GO


CREATE TABLE FINE_CONTRACT(
	FINECONTRACT_ID INT PRIMARY KEY IDENTITY(1,1),
	STAFF_ID INT NOT NULL,
	CONTRACT_ID INT NOT NULL,
	PENALTYPECENT FLOAT,
	CONTENT NVARCHAR(MAX),
	FINEDDAY DATETIME, 
	PENALTY FLOAT,
);
GO

ALTER TABLE FINE_CONTRACT
ADD FOREIGN KEY (CONTRACT_ID) REFERENCES CONTRACTS(CONTRACTS_ID);
GO


ALTER TABLE FINE_CONTRACT
ADD FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID);
GO




CREATE TABLE TYPE_TOURIST(
	TYPETOURIST_ID INT PRIMARY KEY IDENTITY(1,1),
	TYPETOURIST_NAME NVARCHAR(250) NOT NULL,
);
GO 

CREATE TABLE CT_TYPETOURIST_BOOKING (
	BOOKING_ID INT NOT NULL,
	TYPA_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	PRICE FLOAT NOT NULL,
	PRIMARY KEY (BOOKING_ID, TYPA_ID),
    FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID),
    FOREIGN KEY (TYPA_ID) REFERENCES TYPE_TOURIST(TYPETOURIST_ID)
);

GO

CREATE TABLE GUIDE(
	GUIDE_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	GUIDE_NAME NVARCHAR(250) NOT NULL,
	PHONENUMBER VARCHAR(10),
	EMAIL VARCHAR(100) NOT NULL,
	GUIDE_ADDRESS NVARCHAR(500),
	SEX BIT,
	WORK_POSITION NVARCHAR(250) NOT NULL,
);
GO 

CREATE TABLE STAFF(
	STAFF_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	STAFF_NAME NVARCHAR(250) NOT NULL,
	PHONENUMBER VARCHAR(10),
	WORK_POSITION NVARCHAR(250) NOT NULL,
	SEX BIT,
	EMAIL VARCHAR(100) NOT NULL,
);
GO

CREATE TABLE SCHEDULE(
	SCHEDULE_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	SCHEDULE_NAME NVARCHAR(500) NOT NULL,
	TOUR_ID INT NOT NULL,
	DESTINATION NVARCHAR(250),
	DEPARTURE_TIME TIME,
	END_TIME TIME
);
GO

ALTER TABLE SCHEDULE
ADD FOREIGN KEY (TOUR_ID) REFERENCES TOUR(TOUR_ID);
GO



CREATE TABLE TOUR_SERVICE(
	SERVICE_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	SERVICES_NAME NVARCHAR(500) NOT NULL,
	PRICE FLOAT,
	DESCRIPTIONS NVARCHAR(MAX) 
);
GO

CREATE TABLE CT_SCHEDULE_SERVICE (
    SERVICE_ID INT NOT NULL,
    SCHEDULE_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	PRICE FLOAT,
    PRIMARY KEY (SERVICE_ID, SCHEDULE_ID),
    FOREIGN KEY (SERVICE_ID) REFERENCES TOUR_SERVICE(SERVICE_ID),
    FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(SCHEDULE_ID)
);




